spring:
  main:
    banner-mode: 'off'
  application:
    name: spring-profiles
  thymeleaf:
    mode: XHTML
    cache: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    connection-timeout: 10000
    initial-size: 5
    max-active: 8
    max-idle: 8
    min-idle: 3
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: none
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
  h2:
    console:
      enabled: false
  mail:
    default-encoding: UTF-8
    host: smtp.mail.yahoo.com
    password: null
    port: 587
    protocol: smtp
    username: null
    properties:
      mail.smtp.auth: true
  mvc:
    locale: en_US
security:
  basic:
    enabled: false
  user:
    name: julius
    password: password
logging:
  level:
    root: error
    com.jipasoft: debug
    com.github.mongobee: info
    com.zaxxer.hikari: warn